### ISSUE TITLE
Error with S1 24.2.2

### ISSUE THREAD

**Issue by miawri** [munkireport/sentinelone#11]
Running sentinelone.py
    sentinelone.py Error: Traceback (most recent call last):
  File "/usr/local/munkireport/scripts/sentinelone.py", line 79, in <module>
    main()
  File "/usr/local/munkireport/scripts/sentinelone.py", line 43, in main
    agent_data = get_status_data("Agent")
  File "/usr/local/munkireport/scripts/sentinelone.py", line 34, in get_status_data
    return dict([list(map(str.strip, s.split(':', 1))) for s in out.split('\n')[:-1]])
ValueError: dictionary update sequence element #3 has length 1; 2 is required
WARNING: sentinelone.py return code: 1

It appears that the output of sentinelctl status "Missing Authorizations" is missing the colon in 24.2.2 -

   Install Date:                           8/28/24, 2:06:24 PM
   Missing Authorizations
   ES Framework:                           started

I shall put in a ticket to S1 about the issue and suggest they create something that can dump the agent info into a plist whilst I'm at it.

**Comment by tuxudo** [comment]
Version v3.1 of the module should fix this. Please let me know if it doesn't.
